import ollama  # Importing Ollama for AI-generated text processing

def generate_outline(content):
    """
    Generates a structured blog outline based on the provided research content.

    Args:
        content (str): The research data to structure into an outline.

    Returns:
        str: A structured blog outline generated by the AI model.
    """
    
    # Define the prompt to guide the AI in generating an outline
    prompt = f"""
    Generate a structured blog outline based on the research below:

    {content}

    Structure:
    - H1: Main Title
        Introduction
      - H2: Section 1
        - H3: Subsection 1.1
        - H3: Subsection 1.2
        
        and so on...
        - Conclusion
    """

    # Send the request to the AI model and get the response
    response = ollama.chat(model="gemma:2b", messages=[{"role": "user", "content": prompt}])
    
    return response["message"]["content"]


def plan(content):
    """
    Wrapper function to generate a blog outline from research content.

    Args:
        content (str): The research data.

    Returns:
        str: The generated outline.
    """
    
    return generate_outline(content)

